# --- 敌人战斗数据定义（原 main.py load_map 内联 dict 搬来） ---

# 废弃机器人：1-3 与 2-3 两份实例共享同一份数据，id 在生成时区分
ABANDONED_ROBOT_DATA = {
    "name": "废弃机器人",
    "hp": 80,
    "skills": ["escape_dust"],
    "acts": ["观察"],
    "image_folder": "characters/enemies/abandoned_robot",
    "image_prefix": "abandoned_robot",
    "is_grid": True,
    "bgm": "audio/bgm/hi.mp3",
}

BATTLE_DATA = {
    "ghost_samurai": {
        "id": "pipe_2_2_boss",
        "boss_id": "pipe_2_2_boss",
        "name": "鬼武士",
        "hp": 120,
        "skills": ["dark_orb", "samurai_fire_walls", "samurai_gravity_jump"],
        "acts": ["看破"],
        "image_folder": "characters/enemies/samurai_ghost",
        "image_prefix": "samurai_ghost",
        "is_grid": True,
        "bgm": "audio/bgm/brutal.mp3",
    },
    "variable": {
        "id": "snow_1_2_variable",
        "name": "变量",
        "hp": 50,
        "skills": ["laser", "cube", "random_particles"],
        "acts": ["嘲讽", "观察"],
        "image_folder": "characters/enemies/berserk_variable/berserk_variable.png",
        "image_prefix": "variable",
        "is_grid": True,
        "bgm": "audio/bgm/monster_song.mp3",
    },
    "berserk_laser": {
        "id": "pipe_nightmare_1_laser",
        "name": "暴走变量_激光",
        "hp": 80,
        "skills": ["laser", "cube", "random_particles"],
        "acts": ["观察"],
        "image_folder": "characters/enemies/variable_laser/variable_laser_透明.png",
        "image_prefix": "variable_laser",
        "is_grid": True,
        "bgm": "audio/bgm/monster_song.mp3",
    },
    "berserk_jump": {
        "id": "pipe_nightmare_1_jump",
        "name": "暴走变量_跳跃",
        "hp": 80,
        "skills": ["laser", "cube", "random_particles"],
        "acts": ["观察"],
        "image_folder": "characters/enemies/variable_jump/variable_jump透明.png",
        "image_prefix": "variable_jump",
        "is_grid": True,
        "bgm": "audio/bgm/monster_song.mp3",
    },
    "failure": {
        "id": "failure_enemy_01",
        "name": "失败之作",
        "hp": 100,
        "skills": ["noise_attack"],
        "acts": ["聆听"],
        "image_folder": "characters/enemies/failure_boss",
        "image_prefix": "failure",
        "bgm": "audio/bgm/old_doll.mp3",
        "bgm_start": 4.0,
        "bgm_volume": 0.5,
    },
    "black_ranger": {
        "name": "黑游侠EX",
        "hp": 150,
        "skills": ["black_ranger_a", "black_ranger_b", "black_ranger_c"],
        "acts": ["嘲讽", "观察"],
        "boss_id": "base_5_boss",
        "bgm": "audio/bgm/heroism.mp3",
        "image_folder": "characters/enemies/black_ranger",
        "image_prefix": "black_ranger",
        "is_grid": True,
        "flip": True,
    },
    "machine_soldier": {
        "id": "base_2_machine",
        "name": "机凯种",
        "hp": 50,
        "skills": ["ruin_cutting_sequence", "laser_network"],
        "acts": ["嘲讽", "观察"],
        "image_folder": "characters/enemies/machine_soldier",
        "image_prefix": "jikaizhong",
        "is_grid": True,
        "bgm": "audio/bgm/machine_knight.mp3",
        "bgm_start": 17.5,
    },
    "admin": {
        "id": "base_3_admin",
        "name": "admin",
        "hp": 100,
        "skills": ["admin_shield", "admin_laser_cut", "admin_particle_sphere"],
        "acts": ["嘲讽", "观察"],
        "image_folder": "characters/enemies/rebel_leader",
        "image_prefix": "rebel_leader",
        "is_grid": True,
        "bgm": "audio/bgm/the_fish.mp3",
        "anim_speed": 12,
    },
}
